# Generated by Django 4.2.14 on 2024-08-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_test_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 12, 10, 20, 376175, tzinfo=datetime.timezone.utc), verbose_name='pub_date'),
        ),
    ]
