# Generated by Django 4.2.14 on 2024-08-08 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_pub_date_uniquevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 16, 48, 21, 579497, tzinfo=datetime.timezone.utc), verbose_name='pub_date'),
        ),
    ]
